version: '2'
services:
    water-app:
        image: water
        external_links:
            - water-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=water
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    water-mongodb:
        extends:
            file: mongodb.yml
            service: water-mongodb
