version: '2'
services:
    water-mongodb:
        container_name: water-mongodb
        image: mongo:3.3.9
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/water/mongodb/:/data/db/
